### ISSUE TITLE
Invalid API key error

### ISSUE THREAD

**Issue by anand853** [detectlanguage/detectlanguage-java#3]
Im getting below error
Exception in thread "main" com.detectlanguage.errors.APIError: Invalid API key
	at com.detectlanguage.Client.processResponse(Client.java:72)
	at com.detectlanguage.Client.execute(Client.java:54)
	at com.detectlanguage.DetectLanguage.detect(DetectLanguage.java:31)
	at com.sele.test.com.sele.test.App.main(App.java:57)

code i have used

		List<Result> results = DetectLanguage.detect("key");

		Result result = results.get(0);

		System.out.println("Language: " + result.language);
		// System.out.println("Is reliable: " + result.reliable);
		System.out.println("Confidence: " + result.confidence);

**Comment by laurynas** [comment]
Have you configured your API key?

It should be set like this: 

```java
DetectLanguage.apiKey = "YOUR KEY";
```

You can get your free API key at https://detectlanguage.com/
